name: CI

on:
  push:
    branches: ["**"]

jobs:
  build-server:
    name: Build Server Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build server Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          tags: real-time-log-viewer-server:${{ github.sha }}
